export const API_CONFIG = {
  RESPONSE_PER_PAGE: 5,
  MINIMUM_PRICE: 0.001,
  MAXIMUM_PRICE: Number.MAX_VALUE,
  MINIMUM_RATING: 1,
  MAXIMUM_RATING: 5,
  MINIMUM_PAGE_INDEX: 1,
  MINIMUM_PAGE_SIZE: 1,
  MAXIMUM_PAGE_SIZE: 50,
};

// ! TODO: Update at prod
export const BASE_URL = 'http://localhost:3000';
