export const API_CONFIG = {
  RESPONSE_PER_PAGE: 5,
  MINIMUM_PRICE: 0.001,
  MAXIMUM_PRICE: Number.MAX_VALUE,
  MINIMUM_RATING: 1,
  MAXIMUM_RATING: 5,
  MINIMUM_PAGE_INDEX: 1,
  MINIMUM_PAGE_SIZE: 1,
  MAXIMUM_PAGE_SIZE: 50,
  MINIMUM_STOCK: 1,
  MINIMUM_DISCOUNT_PERCENTAGE: 0,
  MAXIMUM_DISCOUNT_PERCENTAGE: 99,
};
